wm: account for the fact that uevent state may be null
Observed with Lindroid:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference

Change-Id: If87a41ffdcd83d4741730de8512a09e29d13c4fb